'\" t
.\"     Title: minesweeper
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/11/2020
.\"    Manual: Games Manual
.\"    Source: DesktopGames 1.0.0
.\"  Language: English
.\"
.TH "MINESWEEPER" "6" "12/11/2020" "DesktopGames 1\&.0\&.0" "Games Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
minesweeper \- A Minesweeper clone
.SH "SYNOPSIS"
.sp
\fBminesweeper\fR [\fB\-b\fR \fIbombs\fR] [\fB\-c\fR \fIcolumns\fR] [\fB\-r\fR \fIrows\fR] [\fB\-s\fR \fIseed\fR]
.SH "DESCRIPTION"
.sp
A Minesweeeper game written in GTK3+, modelled after the Windows XP Minesweeper
.PP
\fB\-b\fR \fIbombs\fR
.RS 4
Place
\fIbombs\fR
bombs on the playing field
.RE
.PP
\fB\-c\fR \fIcolumns\fR
.RS 4
Make the board
\fIcolumns\fR
cells wide
.RE
.PP
\fB\-h\fR
.RS 4
Print a simple help message
.RE
.PP
\fB\-r\fR \fIrows\fR
.RS 4
Make the board
\fIrows\fR
cells high
.RE
.PP
\fB\-s\fR \fIseed\fR
.RS 4
Generate the board using random seed
\fIseed\fR
instead of the current epoch time
.RE
.SH "AUTHORS"
.sp
Brandon Sakai <brandon\&.sakai@gmail\&.com>
